import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-manager-transfer-request',
  templateUrl: './manager-transfer-request.component.html',
  styleUrls: ['./manager-transfer-request.component.scss']
})
export class ManagerTransferRequestComponent implements OnInit {

  constructor() { }

  transferRequestsList = [
    {
      collertorName: 'عامر فؤاد',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
  ]
  transferRequestsList_ = [
    {
      collertorName: 'عامر فؤاد',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
    {
      collertorName: 'عامر عثمان',
      phone: '0589431274',
      orderNumber: '1	',
      orderDate: '2 / 1 / 1446',
      bill: '3000',
      orderStatus: 'تم التحويل',
      notes: '',
    },
  ]

  ngOnInit(): void { }

  filter_collectors(user_filter) {
    this.transferRequestsList = this.transferRequestsList_
    this.transferRequestsList = this.transferRequestsList.filter((data) => {
      return data.collertorName.includes(user_filter)
    })
  }

}
